repos:
  - repo: local
    hooks:
      - id: flake8
        name: flake8
        entry: poetry run flake8
        language: system
        files: '^(src)/'
        exclude: '^(src)/__init__.py'

      - id: pylint
        name: pylint
        entry: poetry run pylint
        language: system
        files: '^(src)/'
        args:
          - --rcfile=pylintrc
